### ISSUE TITLE
4.2.0 regression due to new #inspect method

### ISSUE THREAD

**Issue by TiagoCardoso1983** [rosenfeld/sequel-devise#14]
Just so that you are aware: https://github.com/plataformatec/devise/issues/4187

This is quite ugly and is probably something that the devise guys will fix shortly, but that #serializable_hash thing seems important. Or maybe not? Should it be reimplemented here, or it's not policy of the gem to patch all methods out of the scope of active model and orm adapter?

**Comment by rosenfeld** [comment]
Hi @TiagoCardoso1983. This gem is basically a set of methods that Devise requires being added to the module which is included in the User class, so yes, it currently fits into the scope and we should probably add it to sequel-devise and maybe I'll do it today.

But I'd like to warn you that this entire gem doesn't feel right to me since Devise itself doesn't seem to have any intentions on either fully supporting `orm_adapter` or supporting Sequel and I decided I'm no longer interested in having to update this gem on every new Devise's release when I upgrade, specially when the application I maintain doesn't take much advantage of Devise. We implement custom strategies, have lots work-arounds to make Devise work the way we want and so on. So I've already decided that I should be moving out of Devise and will probably implement everything we need for authentication (we already have most of them implemented in the app) in the application itself.

So, be warned that once I move out of Devise this gem will be mostly unsupported (actually it's not greatly supported already as it doesn't have any tests and I only use a few features from Devise, so those are the ones I test against manually). I can review patches or even add some new method, but since I wouldn't be using it myself, I'm not sure this approach would be reliable (the current approach already isn't much reliable anyway).

So, if you are interested in taking over this project, please let me know.

**Comment by rosenfeld** [comment]
@TiagoCardoso1983 if this is good enough for you I can release a new version with this change. Please let me know if you have any comments:

https://github.com/rosenfeld/sequel-devise/commit/a916ef5127c0073334ec1543952f12137755cd3d

**Comment by rosenfeld** [comment]
I've just released 0.0.9.

**Comment by TiagoCardoso1983** [comment]
Thx, I'll have a look next Monday. I've used this gem as a stepping stone to move this standard rails app into something else, and the orm was the first step. As it uses a small fraction from the features in devise, I can imagine moving away from it sooner rather than later. So although of great help, this gem is just an help for the transition, I just thought you wanted to be up to date on the state of devise.

**Comment by rosenfeld** [comment]
Yes, thanks for reporting, although I haven't experienced this bug myself before you reported, but it's good to have it fixed anyway. There are other steps I should perform before moving the authentication part though. Right now I'm converting the use of js-routes to a custom file with the routes...

**Comment by TiagoCardoso1983** [comment]
@rosenfeld , it did the trick. Thx for the support!
